import 'node:fs';
import 'node:process';
import 'pathe';
import 'fast-glob';
import 'consola';
import 'colorette';
import 'perfect-debounce';
import '@unocss/core';
export { b as build, r as resolveOptions } from './shared/cli.Ex6UAgTe.mjs';
import '@rollup/pluginutils';
import '@unocss/config';
import 'magic-string';
import '@ampproject/remapping';
import 'node:crypto';
import '@unocss/preset-uno';
